version: '3.8'

services:
  app:
    image: linuxlife/ajenti-v:v0.23
    restart: unless-stopped
    volumes:
      - www:/www/:Z
      - home:/home/:Z
      - dehydrated:/etc/dehydrated/:Z
      - mysql:/var/lib/mysql/:Z
      - php:/etc/php/:Z
      - etc_ajenti:/etc/ajenti/:Z
      - ./backup:/backup
    ports:
      - "80:80"
      - "443:443"
      - "7777:22"
      - "8888:8000"
    networks:
      - ajenti-v
volumes:
  www:
  home:
  dehydrated:
  mysql:
  php:
  etc_ajenti:
networks:
  ajenti-v:
